export enum Configuration {
  PORT = 'PORT',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_NAME = 'DB_NAME',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',

  //cloudinary
  CLOUDINARY_USER = 'CLOUDINARY_USER',
  CLOUDINARY_API_KEY = 'CLOUDINARY_API_KEY',
  CLOUDINARY_API_SECRET = 'CLOUDINARY_API_SECRET',

  //AUTH JWT
  JWT_SECRET_KEY = 'JWT_SECRET_KEY',
  JWT_EXPIRES = 'JWT_EXPIRES',

  //FACEBOOK API
  //FACEBOOK_BACKEND_URL={{API_URL}} /v1/auth/facebook/
  FACEBOOK_CLIENT_SECRET = 'FACEBOOK_CLIENT_SECRET',
  FACEBOOK_CLIENT_ID = 'FACEBOOK_CLIENT_ID',
  FACEBOOK_BACKEND_URL = 'FACEBOOK_BACKEND_URL',

  //GOOGLE API
  //GOOGLE_BACKEND_URL= {{API_URL}} /v1/auth/google/
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_BACKEND_URL = 'GOOGLE_BACKEND_URL',
  //SOCIAL_AUTH_CLIENT_URL= {{FrontEnd url para redirigir el social login}}

  SOCIAL_AUTH_CLIENT_URL = 'SOCIAL_AUTH_CLIENT_URL',
  //SEND EMAIL USE OAUTH2
  EMAIL_AUTH_TYPE = 'EMAIL_AUTH_TYPE',
  EMAIL_SERVICE = 'EMAIL_SERVICE',
  EMAIL_HOST = 'EMAIL_HOST',
  EMAIL_PORT = 'EMAIL_PORT',
  EMAIL_SECURE = 'EMAIL_SECURE',
  EMAIL_ALIAS = 'EMAIL_ALIAS',
  EMAIL_USERNAME = 'EMAIL_USERNAME',
  EMAIL_CLIENT_ID = 'EMAIL_CLIENT_ID',
  EMAIL_CLIENT_SECRET = 'EMAIL_CLIENT_SECRET',
  EMAIL_REFRESH_TOKEN = 'EMAIL_REFRESH_TOKEN',
  EMAIL_ACCESS_TOKEN = 'EMAIL_ACCESS_TOKEN',
  EMAIL_TOKEN_EXPIRES = 'EMAIL_TOKEN_EXPIRES',

  //CLIENT VERIFICATION EMAIL TITULAR AND FORGOT PASSOWORD
  CLIENT_URL_VERIFICATION = 'CLIENT_URL_VERIFICATION',
  CLIENT_URL_RESET_PASSWORD = 'CLIENT_URL_RESET_PASSWORD',
  CLIENT_URL_DELETE_USER = 'CLIENT_URL_DELETE_USER',

  TOKENS_BIT_LENGTH = 'TOKENS_BIT_LENGTH',
  TOKENS_ALGORITHM = 'TOKENS_ALGORITHM',
  TOKENS_EXPIRES = 'TOKENS_EXPIRES',
}
